name: Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sundays

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run bandit security checks
      run: |
        pip install bandit
        bandit -r src/ -f json -o bandit-report.json || true
        
    - name: Upload bandit report
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: bandit-report.json
        
    - name: Run safety checks
      run: |
        pip install safety
        safety check -r requirements.txt --json > safety-report.json || true
        
    - name: Upload safety report
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: safety-report.json