apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ai-ml-project-template-cert
  namespace: ai-ml-project-template
  labels:
    app: ai-ml-project-template
spec:
  secretName: ai-ml-project-template-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - ai-ml-project-template
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
  - server auth
  - client auth
  dnsNames:
  - ai-ml-project-template.example.com
  - www.ai-ml-project-template.example.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io