apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ai-ml-project-template-cluster-issuer
  labels:
    app: ai-ml-project-template
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@ai-ml-project-template.example.com
    privateKeySecretRef:
      name: ai-ml-project-template-cluster-issuer-account-key
    solvers:
    - http01:
        ingress:
          class: nginx