apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-ml-config
  labels:
    app: ai-ml-project-template
data:
  mlflow-tracking-uri: "http://mlflow:5000"
  database-host: "db"
  database-port: "5432"
  redis-host: "redis"
  redis-port: "6379"
  app-debug: "false"
  app-host: "0.0.0.0"
  app-port: "8000"
  app-reload: "false"