apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ai-ml-project-template-pdb
  namespace: ai-ml-project-template
  labels:
    app: ai-ml-project-template
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: ai-ml-project-template