apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ai-ml-project-template-prometheus-rules
  namespace: ai-ml-project-template
  labels:
    app: ai-ml-project-template
    prometheus: monitoring
spec:
  groups:
  - name: ai-ml-project-template.rules
    rules:
    - alert: HighCPUUsage
      expr: rate(container_cpu_usage_seconds_total{namespace="ai-ml-project-template"}[5m]) > 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High CPU usage detected
        description: "CPU usage for namespace {{ $labels.namespace }} is above 80% for more than 5 minutes."
    - alert: HighMemoryUsage
      expr: rate(container_memory_usage_bytes{namespace="ai-ml-project-template"}[5m]) > 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High memory usage detected
        description: "Memory usage for namespace {{ $labels.namespace }} is above 80% for more than 5 minutes."
    - alert: HighErrorRate
      expr: rate(http_requests_total{namespace="ai-ml-project-template", status=~"5.."}[5m]) / rate(http_requests_total{namespace="ai-ml-project-template"}[5m]) > 0.05
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High error rate detected
        description: "Error rate for namespace {{ $labels.namespace }} is above 5% for more than 5 minutes."
    - alert: HighLatency
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{namespace="ai-ml-project-template"}[5m])) > 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High latency detected
        description: "95th percentile latency for namespace {{ $labels.namespace }} is above 1 second for more than 5 minutes."
    - alert: LowAvailability
      expr: up{namespace="ai-ml-project-template"} == 0
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: Service is down
        description: "Service in namespace {{ $labels.namespace }} is down for more than 5 minutes."