apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ai-ml-project-template-role
  namespace: ai-ml-project-template
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ai-ml-project-template-rolebinding
  namespace: ai-ml-project-template
subjects:
- kind: ServiceAccount
  name: ai-ml-project-template-sa
  namespace: ai-ml-project-template
roleRef:
  kind: Role
  name: ai-ml-project-template-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-ml-project-template-sa
  namespace: ai-ml-project-template