apiVersion: v1
kind: ResourceQuota
metadata:
  name: ai-ml-project-template-resource-quota
  namespace: ai-ml-project-template
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    pods: "20"
    services: "10"
    secrets: "20"
    configmaps: "20"
    replicationcontrollers: "5"
    resourcequotas: "1"
    services.loadbalancers: "2"
    services.nodeports: "5"
    count/deployments.apps: "10"
    count/replicasets.apps: "20"
    count/statefulsets.apps: "5"
    count/jobs.batch: "10"
    count/cronjobs.batch: "5"
    count/ingresses.networking.k8s.io: "5"
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - high
      - medium
      - low