apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ai-ml-project-template-sealed-secret
  namespace: ai-ml-project-template
  labels:
    app: ai-ml-project-template
spec:
  template:
    metadata:
      name: ai-ml-project-template-secret
      namespace: ai-ml-project-template
      labels:
        app: ai-ml-project-template
    type: Opaque
  encryptedData:
    # NOTE: Actual encrypted data would be placed here
    # This is just a placeholder structure
    # Example key names only - no actual sensitive data
    database-password: <encrypted-value-placeholder>
    api-key: <encrypted-value-placeholder>
    secret-key: <encrypted-value-placeholder>