apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ai-ml-project-template-storage-class
  labels:
    app: ai-ml-project-template
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
mountOptions:
  - debug